### ISSUE TITLE
"Snapshot von `xxx` wurde erstellt" wird im Frontend ausgegeben

### ISSUE THREAD

**Issue by aeberhard** [FriendsOfREDAXO/diff_detect#16]
<details>
<summary>System report (REDAXO 5.15.1, PHP 8.2.8, MariaDB 10.5.19)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.15.1     |

| PHP           |            |
| ------------: | :--------- |
|       Version | 8.2.8      |
|       OPcache | yes        |
|        Xdebug | no         |

| Database      |                 |
| ------------: | :-------------- |
|       Version | MariaDB 10.5.19 |
| Character set | utf8            |

| Server        |            |
| ------------: | :--------- |
|            OS | Linux      |
|          SAPI | cgi-fcgi   |
|     Webserver | Apache     |

| Request       |                  |
| ------------: | :--------------- |
|       Browser | Chrome/114.0.0.0 |
|      Protocol | HTTP/2.0         |
|         HTTPS | yes              |

| Packages            |             |
| ------------------: | :---------- |
|           aceeditor | 1.2.1       |
|              backup | 2.9.0       |
|            be_style | 3.2.0       |
| be_style/customizer | 3.2.0       |
|     be_style/redaxo | 3.2.0       |
|     consent_manager | 4.1.2       |
|             cronjob | 2.10.0      |
|       demo_fullpage | 2.0.8       |
|         diff_detect | 1.1         |
|          httpheader | 1.1.2       |
|             install | 2.11.1      |
|       media_manager | 2.14.0      |
|           mediapool | 2.13.0      |
|            metainfo | 2.10.0      |
|             project | dev         |
|          statistics | 3.0.0beta19 |
|           structure | 2.15.0      |
|   structure/content | 2.15.0      |
|               users | 2.10.0      |
|               yform | 4.1.1       |
|         yform/email | 4.1.1       |
|       yform/manager | 4.1.1       |
|         zip_install | 1.2         |

</details>

**Comment by aeberhard** [comment]
auch mit der aktuellen Version 1.2

**Comment by dergel** [comment]
die ausgaben tauchen nur auf wenn man den cronjob über front und/oder backend erlaubt.. aber natürlich falsch und sollte nun behpben sein .. neue version kommt nachher
